version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:11.12
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          - dependencies-{{ .Environment.CACHE_VERSION }}-

      # Install nuxt dependencies
      - run:
          name: Nuxt dependencies install
          command: NODE_ENV=dev npm ci

      # Keep cache
      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      # Build
      - run:
          name: Build
          command: npm run generate

      - run:
          name: Debug
          command: ls -la; ls -la dist
